name: Build SM8845 Kernel
on:
  push:
    branches: [ oneplus/sm8845_b_16.0.0_ace_6t ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget unzip mkbootimg

      - name: Download Proton‑Clang
        run: |
          wget https://github.com/kdrag0n/proton-clang/releases/download/build-09062024/proton-clang-18.0.0-ubuntu.tar.zst
          tar -I zstd -xf proton-clang-18.0.0-ubuntu.tar.zst
          echo "$PWD/proton-clang/bin" >> $GITHUB_PATH

      - name: Compile Kernel
        env:
          ARCH: arm64
          CROSS_COMPILE: aarch64-linux-gnu-
        run: |
          make generic_auto_defconfig
          make -j$(nproc)

      - name: Generate boot.img
        run: |
          mkbootimg --kernel out/arch/arm64/boot/Image -o boot.img

      - name: Upload boot.img
        uses: actions/upload-artifact@v4
        with:
          name: Compiled‑Boot
          path: boot.img